version: '2'
services:
  nexus-iq-server:
    image: feffi/docker-nexus-iq-server:latest
    hostname: nexus-iq-server
    stdin_open: true
    tty: true
    volumes:
    - nexus-iq-data:/sonatype-work
    - nexus-iq-data/config.yml:/opt/sonatype/iq-server/config.yml
